# n8n feature compose
# 依赖外部网络 ai-server-net 与基础服务 postgres/redis

networks:
  ai-server-net:
    external: true

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: ai-n8n
    restart: unless-stopped
    networks:
      - ai-server-net
    ports:
      - "${BIND_ADDRESS:-127.0.0.1}:${N8N_PORT:-18100}:5678"
    environment:
      # Postgres
      - DB_TYPE=${N8N_DB_TYPE:-postgresdb}
      - DB_POSTGRESDB_HOST=${N8N_DB_HOST:-ai-postgres}
      - DB_POSTGRESDB_PORT=${N8N_DB_PORT:-5432}
      - DB_POSTGRESDB_DATABASE=${N8N_DB_NAME:-ai_server}
      - DB_POSTGRESDB_USER=${N8N_DB_USER:-ai_server}
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_PASSWORD:-ai_server_123}
      # Redis（Bull 队列）
      - QUEUE_BULL_REDIS_HOST=${N8N_REDIS_HOST:-ai-redis}
      - QUEUE_BULL_REDIS_PORT=${N8N_REDIS_PORT:-6379}
      # 其他建议配置
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
    labels:
      com.ai.role: "feature"
      com.ai.module: "n8n"
      com.ai.requires: "postgres,redis"
      com.ai.stack: "ai-server"
