
services:
  dify-api:
    image: langgenius/dify-api:1.7.2
    container_name: ai-dify-api
    restart: unless-stopped
    networks:
      - ai-server-net
    ports:
      - "${BIND_ADDRESS:-127.0.0.1}:${DIFY_API_PORT:-18091}:5001"
    labels:
      com.ai.role: feature
      com.ai.module: dify
      com.ai.requires: postgres,redis
      com.ai.stack: ai-server
    environment:
      # 服务器与迁移
      MIGRATION_ENABLED: "true"
      SECRET_KEY: ${DIFY_SECRET_KEY:-please-change-me}
      # 数据库（使用 infra 中的 Postgres 服务）
      DB_USERNAME: ${POSTGRES_USER:-ai_server}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-ai_server_123}
      DB_HOST: ${POSTGRES_HOST:-postgres}
      DB_PORT: ${POSTGRES_PORT:-5432}
      DB_DATABASE: ${POSTGRES_DB:-ai_server}
      # Redis（使用 infra 中的 Redis 服务）
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      # 存储（OPENDAL 本地文件系统）
      OPENDAL_SCHEME: fs
      OPENDAL_FS_ROOT: /data/storage
      # Dify 官方 CORS 配置
      CORS_ALLOW_ORIGINS: "http://127.0.0.1:${DIFY_WEB_PORT:-18090}"
      WEB_API_CORS_ALLOW_ORIGINS: "*"
      CONSOLE_CORS_ALLOW_ORIGINS: "*"
      CONSOLE_WEB_URL: http://127.0.0.1:${DIFY_WEB_PORT:-18090}
      WEB_API_URL: http://127.0.0.1:${DIFY_API_PORT:-18091}
      APP_WEB_URL: http://127.0.0.1:${DIFY_WEB_PORT:-18090}
    volumes:
      - ai-dify-data:/data
    # 不在 compose 中写 depends_on（跨文件），由主进程按依赖拓扑启动

  dify-web:
    image: langgenius/dify-web:1.7.2
    container_name: ai-dify-web
    restart: unless-stopped
    networks:
      - ai-server-net
    labels:
      com.ai.role: feature
      com.ai.module: dify
      com.ai.requires: postgres,redis
      com.ai.stack: ai-server
    ports:
      - "${BIND_ADDRESS:-127.0.0.1}:${DIFY_WEB_PORT:-18090}:3000"
    environment:
      # Web 通过 API 内部网络访问，无需暴露 API 端口
      DIFY_API_URL: http://ai-dify-api:5001
      # 供前端 JS 使用的 API 根地址（指向宿主映射端口）
      CONSOLE_API_URL: http://127.0.0.1:${DIFY_API_PORT:-18091}
      NEXT_PUBLIC_CONSOLE_API_URL: http://127.0.0.1:${DIFY_API_PORT:-18091}
    # 不在 compose 中写 depends_on（跨文件），由主进程按依赖拓扑启动

networks:
  ai-server-net:
    external: true

volumes:
  ai-dify-data:
