services:
  dify-api:
    image: langgenius/dify-api:1.7.2
    container_name: ai-dify-api
    restart: unless-stopped
    networks:
      - ai-server-net
    ports:
      - 127.0.0.1:18091:5001
    labels:
      com.ai.role: feature
      com.ai.module: dify
      com.ai.requires: postgres,redis
      com.ai.stack: ai-server
    environment:
      MIGRATION_ENABLED: 'true'
      SECRET_KEY: please-change-me
      DB_USERNAME: ai_server
      DB_PASSWORD: ai_server_123
      DB_HOST: postgres
      DB_PORT: '5432'
      DB_DATABASE: ai_server
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      OPENDAL_SCHEME: fs
      OPENDAL_FS_ROOT: /data/storage
      CORS_ALLOW_ORIGINS: http://127.0.0.1:18090
      WEB_API_CORS_ALLOW_ORIGINS: '*'
      CONSOLE_CORS_ALLOW_ORIGINS: '*'
      CONSOLE_WEB_URL: http://127.0.0.1:18090
      WEB_API_URL: http://127.0.0.1:18091
      APP_WEB_URL: http://127.0.0.1:18090
      PLUGIN_DAEMON_URL: http://ai-dify-plugin-daemon:5002
      PLUGIN_DIFY_INNER_API_KEY: QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1
      INNER_API_KEY_FOR_PLUGIN: QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1
    volumes:
      - ai-dify-data:/data
  dify-web:
    image: langgenius/dify-web:1.7.2
    container_name: ai-dify-web
    restart: unless-stopped
    networks:
      - ai-server-net
    labels:
      com.ai.role: feature
      com.ai.module: dify
      com.ai.requires: postgres,redis
      com.ai.stack: ai-server
    ports:
      - 127.0.0.1:18090:3000
    environment:
      DIFY_API_URL: http://ai-dify-api:5001
      CONSOLE_API_URL: http://127.0.0.1:18091
      NEXT_PUBLIC_CONSOLE_API_URL: http://127.0.0.1:18091
  dify-plugin-daemon:
    image: langgenius/dify-plugin-daemon:0.2.0-local
    container_name: ai-dify-plugin-daemon
    restart: unless-stopped
    networks:
      - ai-server-net
    labels:
      com.ai.role: feature
      com.ai.module: dify
      com.ai.requires: postgres,redis
      com.ai.stack: ai-server
    environment:
      DB_USERNAME: ai_server
      DB_PASSWORD: ai_server_123
      DB_HOST: postgres
      DB_PORT: '5432'
      DB_DATABASE: ai_server_plugin
      SERVER_PORT: 5002
      SERVER_KEY: lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi
      MAX_PLUGIN_PACKAGE_SIZE: 52428800
      PPROF_ENABLED: 'false'
      DIFY_INNER_API_URL: http://ai-dify-api:5001
      DIFY_INNER_API_KEY: QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1
      PLUGIN_REMOTE_INSTALLING_HOST: 0.0.0.0
      PLUGIN_REMOTE_INSTALLING_PORT: 5003
      PLUGIN_WORKING_PATH: /app/storage/cwd
      FORCE_VERIFYING_SIGNATURE: 'true'
      PYTHON_ENV_INIT_TIMEOUT: 120
      PLUGIN_MAX_EXECUTION_TIMEOUT: 600
      PLUGIN_STDIO_BUFFER_SIZE: 1024
      PLUGIN_STDIO_MAX_BUFFER_SIZE: 5242880
      PLUGIN_STORAGE_TYPE: local
      PLUGIN_STORAGE_LOCAL_ROOT: /app/storage
      PLUGIN_INSTALLED_PATH: plugin
      PLUGIN_PACKAGE_CACHE_PATH: plugin_packages
      PLUGIN_MEDIA_CACHE_PATH: assets
    volumes:
      - ai-dify-plugin-data:/app/storage
networks:
  ai-server-net:
    external: true
volumes:
  ai-dify-data: null
  ai-dify-plugin-data: null
